export const FREESOUND_API_KEY = 'eToc2P9I24psIWSbd1ga5ICs1PYdhtcFJmLxVItx';
export const FREESOUND_CLIENT_ID = 'qALGlVBP9kxq5nAOybXL';

export const SEARCH_QUERIES = [
  'water drip',
  'metal resonance',
  'wind chime',
  'glass clink',
  'bird call forest',
  'thunder distant',
  'rain drops',
  'bell ring',
  'wood creak',
  'stone scrape',
  'singing bowl',
  'harp pluck',
  'chime tone',
  'ice crack',
  'cave drip',
  'ocean wave',
  'insect buzz',
  'train horn distant',
  'door hinge',
  'chain rattle',
  'ceramic tap',
  'flute breath',
  'gong hit',
  'crystal tone',
  'footstep gravel',
  'paper rustle',
  'whoosh air',
  'click mechanical',
  'piano single note',
  'bow string',
];
